#
# Refer to https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter
#
restartPolicy: Always

image:
  repository: prom/blackbox-exporter
  tag: v0.12.0
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
affinity: {}

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"

resources:
  limits:
    memory: 300Mi
    cpu: 1
  requests:
    memory: 50Mi
    cpu: 0.2

service:
  annotations: {}
  type: ClusterIP
  port: 9115

podAnnotations: {}
extraArgs: []
replicas: 1



## Monitors ConfigMap changes and POSTs to a URL
## Ref: https://github.com/jimmidyson/configmap-reload
##
configmapReload:
  name: configmap-reload
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.2.2
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 300Mi
      cpu: 0.5
    requests:
      memory: 50Mi
      cpu: 0.1
